[package]
name = "etc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustfmt = "0.10.0"
clippy = "0.0.302"
reqwest = { version = "0.11",features = ["blocking"]}
html2md = "0.2"